Conquer-or-Be-Condemned/CBC

- Assets/TextMesh Pro 2.meta
- Assets/TextMesh Pro/Documentation 2.meta
- Assets/TextMesh Pro/Examples & Extras 2.meta
- Assets/TextMesh Pro/Fonts 2.meta
- Assets/TextMesh Pro/Resources 2.meta
- Assets/TextMesh Pro/Shaders 2.meta
- Assets/TextMesh Pro/Sprites 2.meta
> Delete : Duplicated Files

- Assets/Scripts/Player/Player.cs
> Feature : UI template

- Assets/Scenes/UI Test.unity
- Assets/Scripts/Tower/CamoTurret.cs
- Assets/Scripts/UI & Manager/TowerManager.cs
- Assets/Scripts/UI & Manager/TowerManager.cs.meta
- Tower의 수 등을 관리하는 TowerManager 생성
- TowerInfo Text는 초안만 완성
> Feature : TowerManager and TowerInfo

- Assets/Prefabs/Tower/ControlUnit.prefab
- Assets/Prefabs/Tower/Turrets/CamoTurret LV1.prefab
- Assets/Scripts/Tower/ActivateTower.cs
- Assets/Scripts/Tower/ActivateTower.cs.meta
- Assets/Scripts/Tower/CamoTurret LV1.cs
- Assets/Scripts/Tower/CamoTurret LV1.cs.meta
- Assets/Scripts/Tower/CamoTurretLV2.cs
- Assets/Scripts/Tower/CamoTurretLV3.cs
- Assets/Scripts/Tower/DefaultTurret.cs
- Assets/Scripts/Tower/DefaultTurret.cs.meta
- Assets/Scripts/Tower/MissileTurretLV1.cs
- Assets/Scripts/UI & Manager/AlertManager.cs
- Assets/Sprites/Player/space man.png.meta
추후 LV2,LV3 캐모 터렛에 상속 예정, 미사일 터렛 레벨1도 동일
> Feat: DefaultTurret 스크립트 생성 후 CamoTurretLV1.cs에 상속

- Assets/Explode.cs
- Assets/Prefabs/Tower/Weapons/Missile.prefab
- Assets/Scripts/Tower/CamoTurret LV1.cs
- Assets/Scripts/Tower/CamoTurretLV2.cs
- Assets/Scripts/Tower/CamoTurretLV3.cs
- Assets/Scripts/Tower/ControlUnitStatus.cs
- Assets/Scripts/Tower/DefaultTurret.cs
- Assets/Scripts/Tower/Missile.cs
- Assets/Scripts/Tower/MissileTurretLV1.cs
- Assets/Scripts/UI & Manager/TowerManager.cs
- Packages/packages-lock.json
- ProjectSettings/ProjectVersion.txt
이제 미사일 터렛은 범위내에 적이 두마리 이상일 때 그 둘의 가운데 좌표로 회전함
캐논 터렛 레벨 2,3 상속 완료
> Feat: 미사일 터렛 회전 방향 수정 

- Assets/Animation/Animations/UI/Loading.meta
- Assets/Animation/Animations/UI/Loading/Loading.controller
- Assets/Animation/Animations/UI/Loading/Loading.controller.meta
- Assets/Animation/Animations/UI/Loading/LoadingRotate.anim
- Assets/Animation/Animations/UI/Loading/LoadingRotate.anim.meta
- Assets/Animation/Animations/UI/SelectScene/PlanetSet.controller
- Assets/Animation/Animations/UI/SelectScene/PlanetSet.controller.meta
- Assets/Animation/Animations/UI/SelectScene/PlanetSetHide.anim
- Assets/Animation/Animations/UI/SelectScene/PlanetSetHide.anim.meta
- Assets/Animation/Animations/UI/SelectScene/PlanetSetShow.anim
- Assets/Animation/Animations/UI/SelectScene/PlanetSetShow.anim.meta
- Assets/Animation/Animations/UI/SelectScene/Stage_1.controller
- Assets/Prefabs/Tower/Turrets/MissileTurret LV1 Variant.prefab
- Assets/Scenes/Loading.unity
- Assets/Scenes/Main.unity
- Assets/Scenes/StageMenu.unity
- Assets/Scripts/Tower/ControlUnitStatus.cs
- Assets/Scripts/Tower/DefaultCanonTurret.cs
- Assets/Scripts/Tower/DefaultMissileTurret.cs
- Assets/Scripts/UI & Manager/AlertManager.cs
- Assets/Scripts/UI & Manager/GameManager.cs
- Assets/Scripts/UI & Manager/LoadingManager.cs
- Assets/Scripts/UI & Manager/SceneController.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Assets/Scripts/UI & Manager/TowerManager.cs
- UI 디테일 추가
- Missile Turret과 연동 작업
- Control Unit Power 판정 변경(Power 충전에 Delay 부여)
- etc.
> Feature : UIs Detail, Relation with Missile

- Assets/Prefabs/Monsters/Treant.prefab
- Assets/Scripts/Monster/Monster.cs
- Assets/Scripts/Monster/Treant/Treant.cs
- Assets/Scripts/Tower/ControlUnitStatus.cs
- 몬스터의 플레이어 탐지 범위 설정(detectionRange)
- 탐지 범위 벗어날 시, 제어장치로 몬스터 접근
- 제어장치(ControlUnit)의 각 장치에 accessPoints 설정
- 체력바 위치 설정
> feat: Set Detection Rage, Fix Monster HealthBar, Add Control Unit Access Points

- Assets/Prefabs/Tower/ControlUnit.prefab
ControlUnit Prefabs에 Access Points 추가
> feat: ControlUnit Prefabs Add Access Points

- Assets/Scenes/Main.unity
- Assets/Scenes/Stage_1.unity.meta
- Assets/Scripts/UI & Manager/AlertManager.cs
- Assets/Scripts/UI & Manager/CameraController.cs
- Assets/Scripts/UI & Manager/CursorManager.cs
- Assets/Scripts/UI & Manager/GameManager.cs
- Assets/Scripts/UI & Manager/LoadingManager.cs
- Assets/Scripts/UI & Manager/SceneController.cs
- Assets/Scripts/UI & Manager/SiteManager.cs
- Assets/Scripts/UI & Manager/SiteManager.cs.meta
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Assets/Scripts/UI & Manager/TowerManager.cs
- Assets/Scripts/UI & Manager/UICUInfo.cs
- Assets/Scripts/UI & Manager/UIPlayerHp.cs
- Assets/res/Map/Tileset Topdown - Monster Architect Overworld/0_Overworld/Overworld_Ground.png.meta
- Assets/res/UIs/Wenrexa Assets UI Casual Techno/Blue/Panel05.png.meta
- Assets/res/UIs/Wenrexa Assets UI Casual Techno/Blue/Slider01.png.meta
- Assets/res/UIs/Wenrexa Assets UI Casual Techno/Blue/Slider01_B02.png.meta
- UI 관련 스크립트 주석 추가
- Pause, Setting 메뉴 초안 추가
- SiteManager 추가
> Docs : Add Comments

- Assets/Prefabs/Monsters/Stage_1/GreenGolem.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectedTreant.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectousMushroom.prefab
- Assets/Prefabs/Monsters/Stage_1/Slime.prefab
- Assets/Prefabs/Monsters/Stage_1/SlimeLarge.prefab
- Assets/Prefabs/Monsters/Stage_1/Treant.prefab
- Assets/Prefabs/Player/Player.prefab
- Assets/Prefabs/Player/PlayerBullet.prefab
- Assets/Prefabs/Spawner.meta
- Assets/Prefabs/Spawner/Spawner.prefab
- Assets/Prefabs/Spawner/Spawner.prefab.meta
- Assets/Scenes/Stage_1_Spawner.unity.meta
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Player/playerBullet.cs
- Assets/res/Monster/Monster Packs/Monster Pack 14 (Golems)/Spritesheets/Updated Green Golem/Golem_Green_Attack.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 14 (Golems)/Spritesheets/Updated Green Golem/Golem_Green_Idle.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 14 (Golems)/Spritesheets/Updated Green Golem/Golem_Green_Move.png.meta
> feat: Stage 1 Spawner Setting

- Assets/Prefabs/Monsters/Stage_1/GreenGolem.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectedTreant.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectousMushroom.prefab
- Assets/Prefabs/Monsters/Stage_1/Slime.prefab
- Assets/Prefabs/Monsters/Stage_1/SlimeLarge.prefab
- Assets/Prefabs/Player/Player Variant.prefab
- Assets/Prefabs/Player/Player.prefab
- Assets/Prefabs/Player/PlayerBullet.prefab
- Assets/Scenes/Main.unity
- Assets/Scripts/Monster/WalkAndAttackMonster.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Tower/CanonTurretLv1.cs
- Assets/Scripts/Tower/CanonTurretLv2.cs
- Assets/Scripts/Tower/CanonTurretLv3.cs
- Assets/Scripts/Tower/ControlUnitStatus.cs
- Assets/Scripts/Tower/DefaultMissileTurret.cs
- Assets/Scripts/Tower/MissileTurretLV1.cs
- Assets/Scripts/Tower/MissileTurretLV2.cs
- Assets/Scripts/Tower/MissileTurretLV3.cs
- Assets/Scripts/UI & Manager/AudioManager.cs
- Assets/Scripts/UI & Manager/CameraController.cs
- Assets/Scripts/UI & Manager/GameManager.cs
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/LoadingManager.cs
- Assets/Scripts/UI & Manager/SceneController.cs
- Assets/Scripts/UI & Manager/TowerManager.cs
- 플레이어 코드 수정(공격 함수 분리, 딜레이 부여)
- WalkAndAttackMonster 스크립트 수정 -> CU 공격 안됨 해결
- Stage_1 씬 수정
- 기타 등등
> Feature : Stage_1 etc.

- Assets/Animation/Animations/UI/InGame/HideMenu.anim
- Assets/Animation/Animations/UI/InGame/HideStart.anim
- Assets/Animation/Animations/UI/InGame/HideStart.anim.meta
- Assets/Animation/Animations/UI/InGame/ShowMenu.anim
- Assets/Animation/Animations/UI/InGame/ShowStart.anim
- Assets/Animation/Animations/UI/InGame/ShowStart.anim.meta
- Assets/Animation/Animations/UI/InGame/WaveStart.controller
- Assets/Animation/Animations/UI/InGame/WaveStart.controller.meta
- Assets/Scenes/Main.unity
- Assets/Scripts/Monster/Monster.cs
- Assets/Scripts/Player/PlayerInfo.cs
- Assets/Scripts/Spawner/MonsterSpawner.cs
- Assets/Scripts/UI & Manager/AlertManager.cs
- Assets/Scripts/UI & Manager/AudioManager.cs
- Assets/Scripts/UI & Manager/CursorManager.cs
- Assets/Scripts/UI & Manager/GameManager.cs
- Assets/Scripts/UI & Manager/GeneralManager.cs
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/Singleton.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Assets/Scripts/UI & Manager/TalkManager.cs
- Assets/Scripts/UI & Manager/TalkManager.cs.meta
- Assets/Scripts/UI & Manager/TowerManager.cs
- Assets/Scripts/UI & Manager/UIPlayerHp.cs
- Wave 구성 완료
- 대화 DataBase 초안 구성
- 코드가 조금 복잡할 수 있습니다. 빠르게 하느라 일일히 주석 못달았습니다.. 나중에 달게요
- Monster, Spawner 스크립트 수정
- Player 회복 구현
> Feature : Wave, TalkManager

- Assets/Scripts/Player/Player.cs
> Modify : Player Movement

- Assets/Scripts/Monster/Monster.cs
- die시 애니메이션 멈춤
- speed 0으로 설정
- 1초동안 투명해지면서 없어짐
> chore: die 시 투명도 조절

- Assets/Prefabs/Monsters/Stage_1/GreenGolem.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectedTreant.prefab
- Assets/Prefabs/Monsters/Stage_1/Slime.prefab
- Assets/Prefabs/Monsters/Stage_1/SlimeLarge.prefab
- Assets/Prefabs/Monsters/Stage_1/Treant.prefab
- Assets/Prefabs/Player/Player.prefab
- Assets/Prefabs/Player/PlayerBullet.prefab
- Assets/Prefabs/Tower/ControlUnit.prefab
- Assets/Prefabs/Tower/Turrets/CanonTurret LV1.prefab
- Assets/Prefabs/Tower/Turrets/CanonTurret LV2.prefab
- Assets/Prefabs/Tower/Turrets/CanonTurret LV3.prefab
- Assets/Prefabs/Tower/Turrets/MissileTurret LV1.prefab
- Assets/Prefabs/Tower/Turrets/MissileTurret LV2.prefab
- Assets/Prefabs/Tower/Turrets/MissileTurret LV3.prefab
- Assets/Prefabs/Tower/Weapons/Missile.prefab
- Assets/Scenes/Main.unity
- Assets/Scripts/Player/gunflash.cs
- Assets/Scripts/Tower/ControlUnitStatus.cs
- Assets/Scripts/UI & Manager/AudioManager.cs
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/MiniMapController.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Assets/Scripts/UI & Manager/TalkManager.cs
- 플레이어 충돌 판정 에러 수정
- 발사 오브젝트 표시 로직 수정
- 데모용 스테이지 구성
- 데모용 밸런싱 완료
> Feature: Player Movement, For Demo

- Assets/Scenes/GameOver.unity
- Assets/Scenes/Main.unity
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/SceneController.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Restart 버튼 구현
- GoToMain 버튼 구현
> Feature : Restart

- Assets/Prefabs/Player/LASER_RED.prefab
- Assets/Prefabs/Player/LASER_RED.prefab.meta
- Assets/Prefabs/Player/Player.prefab
- Assets/Prefabs/Player/PlayerBullet.prefab
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Player/PlayerBullet.cs
- Assets/Scripts/Player/playerBullet.cs
- Assets/Sprites/Player/space man.png.meta
- Assets/res/ControlTower/MINING_TOWN/WEAPON/LASER/LASER_RED.png.meta
- mono_crash.0.4.json
> Feat: player bullet asset changed

- Assets/Prefabs/Monsters/HealthBarCanvas.prefab
- Assets/Prefabs/Monsters/Stage_1/GreenGolem.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectedTreant.prefab
- Assets/Prefabs/Monsters/Stage_1/InfectousMushroom.prefab
- Assets/Prefabs/Monsters/Stage_1/Slime.prefab
- Assets/Prefabs/Monsters/Stage_1/SlimeLarge.prefab
- Assets/Prefabs/Monsters/Stage_1/Treant.prefab
- Assets/Scripts/Monster/Monster.cs
- 몬스터 사망 시 polygonCollider 제거
- Capsule Collider 2D 제거
> feat: Remove polygon Collider when dead

- Assets/Prefabs/Overworld_Trees_14.prefab
- Assets/Prefabs/Overworld_Trees_14.prefab.meta
- Assets/Prefabs/Tile Palette/Stage2(ice&moon).prefab
- Assets/Prefabs/Tower/Turrets/New Sprite Atlas.spriteatlasv2
- Assets/Prefabs/Tower/Turrets/New Sprite Atlas.spriteatlasv2.meta
- Assets/Prefabs/WInterTree.prefab
- Assets/Prefabs/WInterTree.prefab.meta
- Assets/Prefabs/Winter Tree Arr.prefab
- Assets/Prefabs/Winter Tree Arr.prefab.meta
- Assets/Scenes/Stage_2(temp).unity.meta
- Assets/Scenes/Stage_2.unity.meta
- Assets/Scripts/Tower/CanonTurretLv1.cs
- Assets/Scripts/Tower/CanonTurretLv2.cs
- Assets/Scripts/Tower/CanonTurretLv3.cs
- Assets/Scripts/Tower/MissileTurretLV1.cs
- Assets/Scripts/Tower/MissileTurretLV2.cs
- Assets/Scripts/Tower/MissileTurretLV3.cs
- ProjectSettings/ProjectSettings.asset
- mono_crash.0.5.json
> Feat : Add stage 2

- Assets/Scripts/UI & Manager/GeneralManager.cs
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/SceneController.cs
> Feature : Clear Buttons

- Assets/Prefabs/Player/Player.prefab
- Assets/Scenes/Main.unity
- Assets/Scenes/StageMenu.unity
- Assets/Scripts/Player/PlayerInfo.cs
- Assets/Scripts/UI & Manager/DataManager.cs
- Assets/Scripts/UI & Manager/EventHandler/UICUHpHandler.cs
- Assets/Scripts/UI & Manager/EventHandler/UIControlUnitHealthHandler.cs
- Assets/Scripts/UI & Manager/EventHandler/UIControlUnitPowerHandler.cs
- Assets/Scripts/UI & Manager/EventHandler/UIPlayerBulletHandler.cs
- Assets/Scripts/UI & Manager/EventHandler/UIPlayerHealthHandler.cs
- Assets/Scripts/UI & Manager/EventHandler/UITurretBulletHandler.cs
- Assets/Scripts/UI & Manager/EventHandler/UITurretMissileHandler.cs
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/ShopManager.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
> Fix : Shop and StageInfoManager

- Assets/Scenes/Main.unity
- Assets/Scripts/Player/FirePoint.cs
- Assets/Scripts/Player/Player.cs
- Assets/Scripts/Player/gunflash.cs
- Assets/Scripts/Player/playerguncontrol.cs
- Assets/Scripts/Tower/ControlUnitStatus.cs
- Assets/Scripts/UI & Manager/CameraController.cs
- Assets/Scripts/UI & Manager/CameraOutlineController.cs
- Assets/Scripts/UI & Manager/CameraOutlineController.cs.meta
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Assets/res/UIs/Music/bgm/Inner Light.mp3.meta
> Feature : CameraOutline

- Assets/Scripts/UI & Manager/SettingManager.cs
- Assets/res/UIs/Wenrexa Assets UI Casual Techno/Blue/MiniBox04.png.meta
- Assets/res/UIs/Wenrexa Interface UI KIT #4/PNG/Icons/Icon34.png.meta
> Feature : Player Bomb UI

- Assets/Animation/Animations/Enemy/Stage_3/ElementalFire/ElementalsFireAnimator.overrideController
- Assets/Animation/Animations/Enemy/Stage_3/ElementalFire/ElementalsFireAnimator.overrideController.meta
- Assets/Animation/Animations/Enemy/Stage_3/ElementalsFire.meta
- Assets/Prefabs/Monsters/Stage_2/WolfBlack.prefab
- Assets/Prefabs/Monsters/Stage_3.meta
- Assets/Prefabs/Monsters/Stage_3/Dragon.prefab
- Assets/Prefabs/Monsters/Stage_3/Dragon.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/ElementalFire.prefab
- Assets/Prefabs/Monsters/Stage_3/ElementalFire.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/Latabi.prefab
- Assets/Prefabs/Monsters/Stage_3/Latabi.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/Projectile.prefab
- Assets/Prefabs/Monsters/Stage_3/Projectile.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/PuppetH.prefab
- Assets/Prefabs/Monsters/Stage_3/PuppetH.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/RedGolem.prefab
- Assets/Prefabs/Monsters/Stage_3/RedGolem.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/Tales5.prefab
- Assets/Prefabs/Monsters/Stage_3/Tales5.prefab.meta
- Assets/Prefabs/Monsters/Stage_3/TalesKnight.prefab
- Assets/Prefabs/Monsters/Stage_3/TalesKnight.prefab.meta
- Assets/res/Monster/Monster Packs/Monster Pack 37 (Elementals 2)/Spritesheets/Elemental Fire 3/Elemental_Fire_3_Attack.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 37 (Elementals 2)/Spritesheets/Elemental Fire 3/Elemental_Fire_3_Move.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 37 (Elementals 2)/Spritesheets/Elemental Fire 3/Elemental_Fire_3_Projectile.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 39 (Elementals 4)/Spritesheets/Elemental Air 3/Elemental_Air_3_Projectile.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 6 (Dragons)/Spritesheets/Updated Dragon/Dragon_Attack.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 6 (Dragons)/Spritesheets/Updated Dragon/Dragon_Idle.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 6 (Dragons)/Spritesheets/Updated Dragon/Dragon_Landing.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 6 (Dragons)/Spritesheets/Updated Dragon/Dragon_LiftOff.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 6 (Dragons)/Spritesheets/Updated Dragon/Dragon_Move.png.meta
> feat: Stage 3 Monster Setting

- Assets/Prefabs/Spawner/SpawnerInBoss_Stage_1.prefab
- Assets/Scenes/Main.unity
- Assets/Scripts/UI & Manager/InGameManager.cs
- Assets/Scripts/UI & Manager/SceneController.cs
- Assets/Scripts/UI & Manager/StageSelectManager.cs
- 스테이지 클리어 시 조건문 추가
- 스테이지 선택 창 워프 버튼 SceneController가 아닌 StageSelectManager에서 관리하도록 변경
> Fix : StageSelectManager, InGameManager

- Assets/Prefabs/Monsters/Stage_2/WolfBlack.prefab
- Assets/Prefabs/Spawner/SpawnerInBoss_Stage_2.prefab
- Assets/Scenes/Main.unity
- Assets/Scripts/Monster/BossMonster2.cs
- Assets/Scripts/Monster/BossMonster2.cs.meta
- Assets/Scripts/UI & Manager/AudioManager.cs
- Assets/Scripts/UI & Manager/EventHandler/Stage2Controller.cs
- Assets/Scripts/UI & Manager/EventHandler/Stage2Controller.cs.meta
- Assets/Scripts/UI & Manager/EventHandler/Stage3Controller.cs
- Assets/Scripts/UI & Manager/EventHandler/Stage3Controller.cs.meta
- Assets/Scripts/UI & Manager/StageInfoManager.cs
- Assets/res/Monster/Monster Packs/Monster Pack 63 (Canines 3)/Spritesheets/Wolf Black/Wolf_Black_Ability.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 63 (Canines 3)/Spritesheets/Wolf Black/Wolf_Black_Attack.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 63 (Canines 3)/Spritesheets/Wolf Black/Wolf_Black_Attack_B.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 63 (Canines 3)/Spritesheets/Wolf Black/Wolf_Black_Idle.png.meta
- Assets/res/Monster/Monster Packs/Monster Pack 63 (Canines 3)/Spritesheets/Wolf Black/Wolf_Black_Move.png.meta
> feat: Stage 2 Boss Sound

- Assets/Prefabs/Monsters/Stage_1/InfectedTreant.prefab
- Assets/Prefabs/Monsters/Stage_1/Leaf 1.prefab
- Assets/Prefabs/Monsters/Stage_1/Leaf_Bullet.prefab
- Assets/Prefabs/Monsters/Stage_1/greencircle.prefab
- Assets/Prefabs/Player/Player.prefab
- Assets/Prefabs/Player/PlayerBullet.prefab
- Assets/Scripts/UI & Manager/DataManager.cs
- Assets/Scripts/UI & Manager/StageInfoManager.cs
> refactor: Stage 1 Monster Balence

- Assets/Prefabs/Player/PlayerBullet.prefab
> refactor: Stage 2 Spawner Setting
